[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.fuckhuawei.xyz", custom_domain = true },
  { pattern = "quay.fuckhuawei.xyz", custom_domain = true },
  { pattern = "gcr.fuckhuawei.xyz", custom_domain = true },
  { pattern = "k8s-gcr.fuckhuawei.xyz", custom_domain = true },
  { pattern = "k8s.fuckhuawei.xyz", custom_domain = true },
  { pattern = "ghcr.fuckhuawei.xyz", custom_domain = true },
  { pattern = "cloudsmith.fuckhuawei.xyz", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.fuckhuawei.xyz", custom_domain = true }
